---

log_dir: /var/log
run_dir: /var/run

supervisor_version: 3.1.3
supervisor_virtualenv: '~/.virtualenvs/supervisor'

supervisord_home: '/usr'
supervisor_home: '/etc/supervisor'
supervisor_config: '{{ supervisor_home }}/supervisord.conf'
supervisor_config_dir: '{{ supervisor_home }}/conf.d'

supervisord_path: '/bin/supervisord'
supervisorctl_path: '{{ supervisor_home }}/bin/supervisorctl'

bin_dir: ~/bin

supervisor_link: off # ~/path/to/symlink
supervisor_link_parent: "{% if supervisor_link %}{{ supervisor_link|dirname }}{% endif %}"

supervisor_http: off
supervisor_http_host: 0.0.0.0
supervisor_http_port: 9001

supervisor_http_auth: off
# supervisor_http_auth:
#   username: foo
#   password: bar

pip_args: off # --index-url=http://my.custom.pypi/"
