---
# i.e. upgrade mesos, templates stay the same...
- name: Restart mesos-master
  service: name=mesos-master state=restarted

- name: Restart mesos-slave 
  service: name=mesos-slave state=restarted
