---
- name: Apt install required system packages.
  yum: pkg=zookeeper state=installed
  tags: bootstrap
 

- name: Overwrite myid file.
  template: src=myid.j2 dest=/etc/zookeeper/conf/myid
  tags: deploy

- name: Overwrite default config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  tags: deploy

- name: Restart zookeeper
  service: name=zookeeper state=restarted enabled=yes
  tags: deploy