---
- hosts: "{{ targethosts }}"
  gather_facts: false
  vars:
    vmcores: 1
    vmmemory: 2048
    vmnetwork_dev: vmxnet3
    vmnetwork_name: VM Network
    baseimage: doche-mesos-base
    basevm_ds: tclouds-vm-instances
    target_ds: tclouds-vm-instances

  tasks:
  - raw: /vmfs/volumes/tclouds-vm-images/scripts/createvm.sh   -t "{{ item.vmName }}" -b "{{ baseimage }}" -c "{{ vmcores }}" -r "{{ vmmemory }}" -n "{{ vmnetwork_name }}" -s "{{ basevm_ds }}" -d "{{ target_ds }}"
   
    with_items:
     - { vmName: 'doche-master-a1'}
     - { vmName: 'doche-master-a2'}
     - { vmName: 'doche-master-a3'}


  
