    
---
- hosts: "{{ targethosts }}"
  gather_facts: false
  vars:
    createvmscript: "{{ lookup('file', '../scripts/createvm.sh') }}"
    datastorename: tcloudsex01-ds01
    vmcores: 1
    vmmemory: 2048
    vmnetwork_dev: vmxnet3
    vmnetwork_name: VM Network
    baseimage: Fedora-Base-Thin/Fedora-Base-Thin.vmdk
    
  tasks:

  - raw: echo '{{ createvmscript }}'  > /tmp/createvm.sh
  - raw: chmod +x /tmp/createvm.sh
  - raw: cat /tmp/createvm.sh


  - raw: /tmp/createvm.sh "{{ datastorename }}" "{{ baseimage }}" "{{ targetvm }}-{{ item }}" "{{ vmcores }}" "{{ vmmemory }}" "{{ vmnetwork_dev }}" "{{ vmnetwork_name }}" 
    with_items:
     - 1
     - 2
     - 3
    
    
  - raw: vim-cmd vmsvc/getallvms
  
  
  