---
#
# Java Install Playbook
#


- hosts: all
  sudo: yes
  remote_user: tclouds
  vars:
    zookeeper_hostnames: zk1.cloud.doche.io:2181,zk2.cloud.doche.io:2181,zk3.cloud.doche.io:2181
    chronos_master: zk2.cloud.doche.io:2181
    mesos_install_mode: "master"
  tasks:
   - raw: hostnamectl set-hostname 'mesos-master-{{zoo_id}}'
   - service: name=firewalld enabled=no state=stopped
   
  
  roles:
    - {role: ../roles/openjdk }
    - {role: ../roles/supervisord }
    - {role: ../roles/zookeeper }
    - {role: ../roles/mesos }
    - {role: ../roles/marathon }
    - {role: ../roles/chronos-bin }
