---
#
# Java Install Playbook
#


- hosts: all
  sudo: yes
  remote_user: tclouds
  vars:
    zookeeper_hostnames: 192.168.2.142:2181,192.168.2.148:2181,192.168.2.114:2181
    mesos_install_mode: "master"
  tasks:
  - hostname: name='mesos-master-{{zoo_id}}'
  
  roles:
    - {role: ../roles/openjdk }
    - {role: ../roles/supervisord }
    - {role: ../roles/zookeeper }
    - {role: ../roles/mesos }

