---
#
# Java Install Playbook
#


- hosts: all
  sudo: yes
  remote_user: tclouds
  vars:
    mesos_install_mode: "image"
    install_mode: "image"
  tasks:
    - raw: hostnamectl set-hostname mesos-master-base
  
  roles:
    - {role: ../roles/openjdk }
    - {role: ../roles/supervisord }
    - {role: ../roles/zookeeper }
    - {role: ../roles/mesos }
    - {role: ../roles/marathon }
    - {role: ../roles/chronos-bin }
