---
#
# Mesos Slave Playbook
#


- hosts: "{{ targethosts }}"
  sudo: yes
  remote_user: tclouds
  vars:
    mesos_install_mode: "slave"
    install_mode: "slave"
    zookeeper_hostnames: zk1.cloud.doche.io:2181,zk2.cloud.doche.io:2181,zk3.cloud.doche.io:2181
    #mesos_slave_attributes: hypervisor:3;region:us;zone:east;type:stateless;os:centos7;grid:doche
  tasks:
  - raw: hostnamectl set-hostname 'mesos-slave-{{id}}'
  - name: copy the docker registry login cfg file
    template: src=templates/dockercfg.j2 dest=/etc/supervisor/conf.d/.dockercfg
  - service: name=firewalld enabled=no state=stopped
  
  roles:
    - {role: ../roles/openjdk }
    - {role: ../roles/supervisord }
    - {role: ../roles/mesos }

