---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add Mesosphere repo
  apt_repository: repo="{{marathon_apt_repo}}" state=present

- name: Install Marathon package
  apt: pkg=marathon={{marathon_version}}-1.0 state=present update_cache=yes
