---
# == Work Dir for replicated log
- name: create work dir
  file: path=/var/mesos state=directory

# == Remove default configs
- name: Remove Default Mesos Configs
  file: state=absent path=/etc/mesos/

- name: Remove Mesos ZK File
  file: state=absent path=/etc/mesos/zk

- name: Remove Default Mesos-Master Config
  file: state=absent path=/etc/mesos-master/

- name: Remove Default Mesos-default Master Config
  file: state=absent path=/etc/default/mesos-master
  
- name: Remove Default Mesos-Slave Config
  file: state=absent path=/etc/mesos-slave/
 
- name: Remove Default Mesos-default Slave Config
  file: state=absent path=/etc/default/mesos-slave  

# == Configure and recreate
- name: Mesos default config file
  template: src=conf-mesos.j2 dest=/etc/default/mesos

- name: Mesos Master config file
  template: src=conf-mesos-master.j2 dest=/etc/default/mesos-master
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: supervisor startup script for mesos master
  template: src=supervisor-mesos-master.conf.j2 dest='{{supervisor_config_dir}}/supervisor-mesos-master.conf'
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-master supervisord

- name: supervisor startup script for mesos slave
  template: src=supervisor-mesos-slave.conf.j2 dest='{{supervisor_config_dir}}/supervisor-mesos-slave.conf'
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-slave supervisord